import type { Metadata } from "next";
import LegalShell from "@/components/LegalShell";
import { COMPANY, TAX_CLAUSE } from "@/lib/company";

export const metadata: Metadata = {
  title: "Terms & Conditions — VissionLink",
  description: "The terms governing the use of VissionLink, operated by BMR Cinema Operation Services.",
};

export default function TermsPage() {
  return (
    <LegalShell title="Terms & Conditions" updated={COMPANY.legalUpdated} active="terms">
      <p>
        These Terms &amp; Conditions (&quot;Terms&quot;) govern your access to and use of <strong>{COMPANY.domain}</strong> and
        the VissionLink rental marketplace (the &quot;Platform&quot;). The Platform is owned and operated by{" "}
        <strong>{COMPANY.legalName}</strong> ({COMPANY.taxType}, TIN {COMPANY.tin}), a sole proprietorship registered in the
        Republic of the Philippines (&quot;VissionLink&quot;, &quot;we&quot;, &quot;us&quot;). By using the Platform you agree to these Terms.
      </p>

      <h2>1. About VissionLink</h2>
      <p>
        VissionLink is a marketplace that connects customers (&quot;Renters&quot;) with independent equipment owners
        (&quot;Owners&quot;) for the rental of film, television, and production gear. VissionLink does not own most of the
        listed equipment; we facilitate discovery, reservation, payment, and coordination between Renters and Owners.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 18 years old and able to enter into a legally binding contract under Philippine law. You are
        responsible for the accuracy of the information you provide.
      </p>

      <h2>3. Reservations &amp; Bookings</h2>
      <ul>
        <li>Submitting a reservation request is an offer to rent; it is confirmed once the downpayment is received and the rental agreement is accepted.</li>
        <li>A <strong>15% reservation downpayment</strong> is paid online to secure the booking.</li>
        <li>The balance is settled per the method chosen at checkout — before/upon handover, in full online (with a full-payment discount), or by post-dated cheque (with a PDC discount). Any security deposit is settled on release.</li>
        <li>Rental rates are quoted per day (one rental day = 24 hours). Final amounts may include logistics/delivery, out-of-town surcharge (15% outside Metro Manila), and operator/crew fees where applicable.</li>
      </ul>

      <h2>4. Payments</h2>
      <p>
        Payments are processed by our third-party payment provider (PayMongo) via card, GCash, Maya, or other supported
        methods. VissionLink does not store full card details. {TAX_CLAUSE} The official receipt issued for any payment is
        governed by Section 8 below.
      </p>

      <h2>5. Use &amp; Care of Equipment</h2>
      <ul>
        <li>Equipment must be used lawfully and only for its intended purpose during the agreed rental period.</li>
        <li>The Renter is responsible for loss, theft, or damage to equipment while in their possession, and may be charged repair or replacement costs and applicable security deposits.</li>
        <li>Late returns may incur additional daily charges. Equipment must be returned in the condition received, ordinary wear excepted.</li>
      </ul>

      <h2>6. Roles &amp; Responsibilities</h2>
      <p>
        Owners are responsible for the accuracy of listings and the condition of their equipment. Renters are responsible
        for their use of the equipment. VissionLink acts as a facilitator and is not a party to the underlying rental beyond
        the services it expressly provides.
      </p>

      <h2>7. Cancellations &amp; Refunds</h2>
      <p>
        Cancellations and refunds are governed by our <a href="/legal/refund">Refund &amp; Cancellation Policy</a>, which
        forms part of these Terms.
      </p>

      <h2>8. Official Receipts</h2>
      <div className="legal-note">
        Any acknowledgment, summary, or provisional receipt generated by the Platform is for reference only and is{" "}
        <strong>not an official receipt</strong>. The official receipt / service invoice for any payment is issued by{" "}
        {COMPANY.legalName} in accordance with its BIR registration.
      </div>

      <h2>9. Prohibited Conduct</h2>
      <p>
        You agree not to misuse the Platform, including fraud, infringing others&apos; rights, sub-renting without consent,
        or using equipment for unlawful activity.
      </p>

      <h2>10. Disclaimers &amp; Limitation of Liability</h2>
      <p>
        The Platform is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law,
        VissionLink is not liable for indirect or consequential damages. Nothing in these Terms limits liability that cannot
        be excluded under the Consumer Act of the Philippines (RA 7394) or other applicable law.
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify {COMPANY.legalName} against claims arising from your breach of these Terms or your misuse of
        the Platform or equipment.
      </p>

      <h2>12. Privacy</h2>
      <p>
        Your use of the Platform is also governed by our <a href="/legal/privacy">Privacy Policy</a>.
      </p>

      <h2>13. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the Republic of the Philippines. Disputes are subject to the exclusive
        jurisdiction of the courts of Parañaque City / Metro Manila, without prejudice to any mandatory consumer venue.
      </p>

      <h2>14. Changes</h2>
      <p>We may update these Terms from time to time. Continued use after changes constitutes acceptance.</p>

      <h2>15. Contact</h2>
      <p>
        {COMPANY.legalName} — {COMPANY.address}. Email{" "}
        <a href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a>.
      </p>
    </LegalShell>
  );
}
