import type { Metadata } from "next";
import LegalShell from "@/components/LegalShell";
import { COMPANY } from "@/lib/company";
import { DOWNPAYMENT_RATE } from "@/lib/rental-pricing";

const dpPct = Math.round(DOWNPAYMENT_RATE * 100);

export const metadata: Metadata = {
  title: "Refund & Cancellation Policy — VissionLink",
  description: "How reservations, downpayments, and refunds are handled on VissionLink.",
};

export default function RefundPage() {
  return (
    <LegalShell title="Refund & Cancellation Policy" updated={COMPANY.legalUpdated} active="refund">
      <p>
        This policy explains how cancellations and refunds are handled for rentals booked through{" "}
        <strong>{COMPANY.domain}</strong>, operated by <strong>{COMPANY.legalName}</strong>. It forms part of our{" "}
        <a href="/legal/terms">Terms &amp; Conditions</a>.
      </p>

      <h2>1. Reservation Downpayment</h2>
      <p>
        Bookings are secured with a <strong>{dpPct}% reservation downpayment</strong> paid online at checkout (or in full,
        if you choose the full-payment option). The downpayment holds the equipment and schedule for your rental window.
      </p>

      <h2>2. Cancellation by the Renter</h2>
      <ul>
        <li><strong>More than 12 hours before the scheduled release:</strong> amounts paid are refundable, less any non-recoverable transaction fees.</li>
        <li><strong>Within 12 hours of the scheduled release:</strong> a <strong>20% cancellation fee</strong> applies; the reservation downpayment may be applied against it.</li>
        <li><strong>After the equipment has been picked up or dispatched:</strong> a <strong>50% fee</strong> applies.</li>
      </ul>

      <h2>3. Cancellation by VissionLink or the Owner</h2>
      <p>
        If we or the Owner cancel a confirmed booking (e.g., equipment becomes unavailable or is not as described), you are
        entitled to a <strong>full refund</strong> of all amounts paid, including the downpayment. Where possible, we will
        offer a comparable replacement instead.
      </p>

      <h2>4. Security Deposit</h2>
      <p>
        No security deposit is collected at online checkout. Where a refundable deposit is required for a specific release,
        the amount is stated on your quotation or rental contract; it is refundable after the equipment is returned and
        inspected, less deductions for loss, damage, late return, or missing accessories.
      </p>

      <h2>5. How Refunds Are Processed</h2>
      <p>
        Approved refunds are returned through the original payment method via our payment provider (PayMongo). Processing
        times depend on the provider and your bank or e-wallet, typically within a few business days. Third-party
        transaction fees may be non-refundable.
      </p>

      <h2>6. Official Receipts &amp; Adjustments</h2>
      <div className="legal-note">
        Refunds and adjustments are reflected in the official receipt / service invoice issued by {COMPANY.legalName} per its
        BIR registration. Any provisional acknowledgment generated by the Platform is for reference only and is not the
        official receipt.
      </div>

      <h2>7. Consumer Rights</h2>
      <p>
        Nothing in this policy limits your rights under the Consumer Act of the Philippines (RA 7394) and other applicable
        law.
      </p>

      <h2>8. Contact</h2>
      <p>
        To request a cancellation or refund, contact {COMPANY.legalName} at{" "}
        <a href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a> with your reservation reference.
      </p>
    </LegalShell>
  );
}
